src/views.py
from .login import login_required
from . import get_db
from flask import (
    Blueprint, render_template, request,
    session, redirect, url_for, send_file, flash
)

main = Blueprint('main', __name__)

@main.route('/')
def home():
    '''
    redirect user to index.html ie sign-in page
    '''
    return redirect(url_for('main.homepage'))


@main.route('/index.html')
def index():
    '''
    renders login page
    '''
    return render_template('index.html')

@main.route('/homepage.html')
def homepage():
    '''
    renders home page
    '''
    return render_template('homepage.html')

@main.route("/sign-up.html")
def sign_up():
    return render_template("sign-up.html")

# Route to serve image file
@main.route('/home')
def get_home_image():
    filename = '../templates/assets/home.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/search')
def get_search_image():
    filename = '../templates/assets/search.png' # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/user')
def get_user_image():
    filename = '../templates/assets/user.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/logo')
def get_logo_image():
    filename = '../templates/assets/logo.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/cravengers')
def get_cravengers_image():
    filename = '../templates/assets/cravengers.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/cravengers-noshadow')
def get_cravengers_noshadow_image():
    filename = '../templates/assets/cravengers-nshadow.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

# homepage assets
@main.route('/controller')
def get_controller_image():
    filename = '../templates/assets/controller.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/eco')
def get_eco_image():
    filename = '../templates/assets/eco.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/location')
def get_location_image():
    filename = '../templates/assets/location.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/rider')
def get_rider_image():
    filename = '../templates/assets/rider.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/food')
def get_food_image():
    filename = '../templates/assets/food.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/trophy')
def get_trophy_image():
    filename = '../templates/assets/trophy.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/letter')
def get_letter_image():
    filename = '../templates/assets/letter.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/founders')
def get_founders_image():
    filename = '../templates/assets/founders.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

# streak assets
@main.route('/bg1')
def get_bg1_image():
    filename = '../templates/assets/streak_bg1.svg'  # Path to your image file
    return send_file(filename, mimetype='image/svg+xml')

@main.route('/bg2')
def get_bg2_image():
    filename = '../templates/assets/streak_bg2.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/flame')
def get_flame_image():
    filename = '../templates/assets/streak_flame.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/fork')
def get_fork_image():
    filename = '../templates/assets/streak_fork.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route('/voucher')
def get_voucher_image():
    filename = '../templates/assets/streak_voucher.png'  # Path to your image file
    return send_file(filename, mimetype='image/png')

@main.route("/adminpage.html")
def adminpage():
    # update session info every time
    user_info = session.get('user_info')
    UID = user_info['UID']
    db = get_db()
    user_info = db.cursor().execute(
        """ select *
            from Users
            where UID = ?""", (UID,)
    ).fetchone()
    session['user_info'] = dict(user_info)

    # fetch shop_info
    shop_info = db.cursor().execute(
        """ select *
            from Stores
            where S_owner = ?""", (UID,)
    ).fetchone()

    # fetch product_info
    product_info = db.cursor().execute(
        """ select *
            from Products
            where P_owner = ?""", (UID,)
    ).fetchall()

    costumer_info = db.cursor().execute(
        """ select *
            from Users"""
    ).fetchall()

    image_info = [tple['P_image'].decode("utf-8") for tple in product_info]

    return render_template("adminpage.html", user_info=user_info, shop_info=shop_info, product_info=product_info, image_info=image_info, costumer_info=costumer_info)



@main.route("/userpage.html")
@login_required
def userpage():
    # update session info every time
    user_info = session.get('user_info')
    UID = user_info['UID']
    db = get_db()
    user_info = db.cursor().execute(
        """ select *
            from Users
            where UID = ?""", (UID,)
    ).fetchone()
    session['user_info'] = dict(user_info)

    # fetch shop_info
    shop_info = db.cursor().execute(
        """ select *
            from Stores
            where S_owner = ?""", (UID,)
    ).fetchone()

    # fetch product_info
    product_info = db.cursor().execute(
        """ select *
            from Products
            where P_owner = ?""", (2,)
    ).fetchall()

    image_info = [tple['P_image'].decode("utf-8") for tple in product_info]

    return render_template("userpage.html", user_info=user_info, shop_info=shop_info, product_info=product_info, image_info=image_info)



@main.route("/productlistpage.html")
@login_required
def productlistpage():
    # update session info every time
    user_info = session.get('user_info')
    UID = user_info['UID']
    db = get_db()
    user_info = db.cursor().execute(
        """ select *
            from Users
            where UID = ?""", (UID,)
    ).fetchone()
    session['user_info'] = dict(user_info)

    # fetch shop_info
    shop_info = db.cursor().execute(
        """ select *
            from Stores
            where S_owner = ?""", (UID,)
    ).fetchone()

    # fetch product_info
    product_info = db.cursor().execute(
        """ select *
            from Products
            where P_owner = ?""", (2,)
    ).fetchall()

    image_info = [tple['P_image'].decode("utf-8") for tple in product_info]

    return render_template("productlistpage.html", user_info=user_info, shop_info=shop_info, product_info=product_info, image_info=image_info)


@main.route("/profilepage.html")
@login_required
def profilepage():
    # update session info every time
    user_info = session.get('user_info')
    UID = user_info['UID']
    db = get_db()
    user_info = db.cursor().execute(
        """ select *
            from Users
            where UID = ?""", (UID,)
    ).fetchone()
    session['user_info'] = dict(user_info)

    # fetch shop_info
    shop_info = db.cursor().execute(
        """ select *
            from Stores
            where S_owner = ?""", (UID,)
    ).fetchone()

    # fetch product_info
    product_info = db.cursor().execute(
        """ select *
            from Products
            where P_owner = ?""", (2,)
    ).fetchall()

    image_info = [tple['P_image'].decode("utf-8") for tple in product_info]

    return render_template("profilepage.html", user_info=user_info, shop_info=shop_info, product_info=product_info, image_info=image_info)


@main.route("/streak.html")
@login_required
def streak():
    # update session info every time
    user_info = session.get('user_info')
    UID = user_info['UID']
    db = get_db()
    user_info = db.cursor().execute(
        """ select *
            from Users
            where UID = ?""", (UID,)
    ).fetchone()
    session['user_info'] = dict(user_info)

    return render_template("streak.html", user_info=user_info)





# @main.route("/nav.html")
# @login_required
# def nav():
#     # update session info every time
#     user_info = session.get('user_info')
#     UID = user_info['UID']
#     db = get_db()
#     user_info = db.cursor().execute(
#         """ select *
#             from Users
#             where UID = ?""", (UID,)
#     ).fetchone()
#     session['user_info'] = dict(user_info)

#     # fetch shop_info
#     shop_info = db.cursor().execute(
#         """ select *
#             from Stores
#             where S_owner = ?""", (UID,)
#     ).fetchone()

#     # fetch product_info
#     product_info = db.cursor().execute(
#         """ select *
#             from Products
#             where P_owner = ?""", (UID,)
#     ).fetchall()

#     image_info = [tple['P_image'].decode("utf-8") for tple in product_info]

#     return render_template("nav.html", user_info=user_info, shop_info=shop_info, product_info=product_info, image_info=image_info)


# @main.route("/edit_location", methods=['POST'])
# @login_required
# def edit_location():
#     user_info = session.get('user_info')
#     UID = user_info['UID']
#     latitude = request.form['latitude']
#     longitude = request.form['longitude']

#     # check any blanks:
#     for k, v in request.form.items():
#         if v == '':

templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Cravengers</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="A ordering system By 12 - Einstein" />
	<meta name="keywords" content="A ordering system By 12 - Einstein" />
	<meta name="author" content="" />

	

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">


	<!-- Modernizr JS -->
	<script src="{{ url_for('static', filename='js/modernizr-2.6.2.min.js') }}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>

<body>

	<!-- Nav -->
	<div class="navbar_home">
        <div class="row">
            <div class="col-xs-6">
                <!-- Return home BTN -->
				<a style="color: black; text-decoration: none;" class="poppins-bold" href="homepage.html">&#x21a9; Return to Home</a>
            </div>
            <div class="col-xs-6" style="text-align: right">
                <div>
                    <a href="#" class="btn__standard" style="margin-right: 10px">
                        <img src="{{ url_for('main.get_search_image') }}" style="width: 20px" />
                    </a>
                    <a href="index.html" class="btn__standard">
                        <img src="{{ url_for('main.get_user_image') }}" style="width: 20px" />
                    </a>
                </div>
            </div>
        </div>
	</div>
	<div class="bg-frntpage">
		<div class="container">
			<!-- Sign-in form -->
			 <div class="page-row">
				<div class="col-md-6">
					<div style="width: 450px;">
						<form action="login" method="post" class="fh5co-form animate-box" data-animate-effect="fadeIn">
							<h2 class="poppins-bold" style="text-align: center;">Log In</h2>
							{% with messages = get_flashed_messages() %}
								{% if messages %}
									{% for message in messages %}
										<p style="color: red; text-align: center; text-transform: uppercase;" class="poppins-bold">{{ message }}</p>
									{% endfor %}
								{% endif %}
							{% endwith %}
							{% block body %}{% endblock %}
							<div class="form-group">
								<label for="Account" class="sr-only poppins-regular">User Name</label>
								<input style="padding-left: 10px; border-bottom: 1px solid #800000;" type="text" class="form-control poppins-regular" id="Account" name="Account" placeholder="User Name" autocomplete="off">
							</div>
							<div class="form-group">
								<label for="password" class="sr-only poppins-regular">Password</label>
								<input style="padding-left: 10px; border-bottom: 1px solid #800000;" type="password" class="form-control poppins-regular" id="password" name="password" placeholder="Password" autocomplete="off">
							</div>
							<div class="form-group poppins-regular" style="margin-bottom: 10px;">
								<input style="width: 100%; background: #800000; color: white; padding: 10px 0px" type="submit" value="Log In" class="btn">
							</div>
							<div class="form-group poppins-regular" style="text-align: center; margin-bottom: 5px;">
								<p>Not registered? <a style="color: #800000;" href="sign-up.html">Sign Up</a> </p>
							</div>
						</form>
					</div>
				</div>

				<!-- Logo -->
				<div class="col-md-6">
					<div style="align-items: center; justify-content: center;">
						<img src="{{ url_for('main.get_logo_image') }}" style="width: 100%; max-width:370px; height: auto; padding-top: 20px;" alt="Cravengers Logo" />
					</div>
				</div>
			 </div>
			
		</div>
	</div>


	<!-- jQuery -->
	<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
	<!-- Bootstrap -->
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
	<!-- Placeholder -->
	<script src="{{ url_for('static', filename='js/jquery.placeholder.min.js') }}"></script>
	<!-- Waypoints -->
	<script src="{{ url_for('static', filename='js/jquery.waypoints.min.js') }}"></script>
	<!-- Main JS -->
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>




</body>

</html>
<style>
	.bg-frntpage {
		background:
		linear-gradient(229deg,#AF191A 10%, #F3BD38 46%);
		min-height: 100vh;
		display: flex;
	}
	.container {
		align-items: center; 
	}
	.page-row {
		display: flex; 
		justify-content: center; 
		gap: 100px; 
		padding-top: 100px;
		margin-left: 100px;
	}
	.col-md-6 {
		display: flex;
		justify-content: center;
		align-items: center;
	}



</style>

templates/sign-up.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Sign Up - Cravengers</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />

	<!-- 
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE 
	DESIGNED & DEVELOPED by FreeHTML5.co
		
	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>

<body>

	<!-- Nav -->
	<div class="navbar_home">
        <div class="row">
            <div class="col-xs-6">
                <!-- Return home BTN -->
				<a style="color: black; text-decoration: none;" class="poppins-bold" href="homepage.html">&#x21a9; Return to Home</a>
            </div>
            <div class="col-xs-6" style="text-align: right">
                <div>
                    <a href="#" class="btn__standard" style="margin-right: 10px">
                        <img src="{{ url_for('main.get_search_image') }}" style="width: 20px" />
                    </a>
                    <a href="index.html" class="btn__standard">
                        <img src="{{ url_for('main.get_user_image') }}" style="width: 20px" />
                    </a>
                </div>
            </div>
        </div>
	</div>
	<div class="bg-frntpage">
		<div class="container">
			<div class="page-row">
				<div class="col-md-6">
					<div style="width: 450px;">
						<form action="register" method="post" id="register" class="fh5co-form animate-box" data-animate-effect="fadeIn">
							<h2 class="poppins-bold" style="text-align: center;">Sign Up</h2>

							<!-- Flash messages -->
							{% with messages = get_flashed_messages() %}
							{% if messages %}
							<ul class="flashes">
								{% for message in messages %}
								<li>{{ message }}</li>
								{% endfor %}
							</ul>
							{% endif %}
							{% endwith %}

							{% block body %}{% endblock %}

							<!-- Step 1 -->
							<div id="step1">
								<div class="form-group">
									<input style="border-bottom: 1px solid #800000" type="text" class="form-control poppins-regular" id="name" name="name" placeholder="Name ex: John Doe" autocomplete="off">
								</div>
								<div class="form-group">
									<input style="border-bottom: 1px solid #800000" type="text" class="form-control poppins-regular" id="phonenumber" name="phonenumber" placeholder="Phone num ex: 9123456789" autocomplete="off">
								</div>
								<div class="form-group">
									<input style="border-bottom: 1px solid #800000" type="text" class="form-control poppins-regular" id="Account" name="Account" placeholder="User Name ex: johndoe" autocomplete="off">
									<div id="msg"></div>
								</div>
								<div class="form-group" style="margin-bottom: 10px;">
									<button type="button" class="btn" style="width: 100%; background: #800000; color: white;" onclick="nextStep()">Next</button>
								</div>
								<div class="form-group poppins-regular" style="text-align: center; margin-bottom: 5px;">
									<p>Already registered? <a style="color: #800000;" href="index.html">Log In</a></p>
								</div>
							</div>

							<!-- Step 2 -->
							<div id="step2" style="display: none;">
								<div class="form-group">
									<input style="border-bottom: 1px solid #800000" type="password" class="form-control poppins-regular" id="password" name="password" placeholder="Password" autocomplete="off">
								</div>
								<div class="form-group">
									<input style="border-bottom: 1px solid #800000" type="password" class="form-control poppins-regular" id="re-password" name="re-password" placeholder="Re-type Password" autocomplete="off">
								</div>
								<div class="form-group" style="display: flex; justify-content: space-between; gap: 10px; margin-bottom: 10px;">
									<button type="button" class="btn poppins-regular" onclick="prevStep()" style="flex: 1; background: #ffffff00; color: black; border: 1px solid black">
										Back
									</button>
									<input type="submit" value="Sign Up" class="btn poppins-regular" style="flex: 1; background: #800000; color: white;">
								</div>

								<div class="form-group poppins-regular" style="text-align: center; margin-bottom: 5px;">
									<p>Already registered? <a style="color: #800000;" href="index.html">Log In</a></p>
								</div>
							</div>
						</form>
					</div>
				</div>	
				<script type="text/javascript">
					$('document').ready(function () {
						$('#Account').on('input', function () {
							$.ajax({
								url: 'http://' + window.location.host + "/register-account-check",
								method: "POST",
								data: $('#Account').serialize(),
								async: false,
								success: function (data) {
									$('#msg').html(data);
								},
								error: function (jqxhr, textStatus, errorThrown) {
									alert("error: " + textStatus)
								}
							})
						});
					});
					
					function nextStep() {
						// Optional: Add basic validation before continuing
						const name = document.getElementById('name').value.trim();
						const phone = document.getElementById('phonenumber').value.trim();
						const username = document.getElementById('Account').value.trim();

						if (!name || !phone || !username) {
							alert('Please fill out all fields.');
							return;
						}

						// Switch form parts
						document.getElementById('step1').style.display = 'none';
						document.getElementById('step2').style.display = 'block';
					}

						function prevStep() {
						document.getElementById('step2').style.display = 'none';
						document.getElementById('step1').style.display = 'block';
					}
				</script>		
				<div class="col-md-6">
					<div style="align-items: center; justify-content: center;">
						<img src="{{ url_for('main.get_logo_image') }}" style="width: 100%; max-width:370px; height: auto; padding-top: 20px;" alt="Cravengers Logo" />
					</div>
				</div>
			</div>
		</div>
	</div>



</body>

</html>
<style>
	.bg-frntpage {
		background:
		linear-gradient(229deg,#AF191A 10%, #F3BD38 46%);
		min-height: 100vh;
		display: flex;
	}
	.container {
		align-items: center; 
	}
	.page-row {
		display: flex; 
		justify-content: center; 
		gap: 100px; 
		padding-top: 80px;
		margin-left: 100px;
	}
	.col-md-6 {
		display: flex;
		justify-content: center;
		align-items: center;
	}

</style>